name: sectiondofus.com
title: SectionDofus.com
plugins: ['jekyll-paginate', 'jekyll-sitemap']
paginate: 5
paginate_path: /archive/:num/
permalink: /article/:title/
url: https://sectiondofus.com
baseurl: ""